---
title: "GI Cancer Education"
---
<br/>

## Patient education resources for GI cancer patients


### Esophageal Cancer

#### Diagnosis and Staging

[Video](https://www.youtube.com/watch?v=aDkgurq17wE) &nbsp; &nbsp; &nbsp; &nbsp; [Slides](slides/02-Eso_Dx_Staging.html) &nbsp; &nbsp; &nbsp; &nbsp; [Handout](slides/02-Eso_Dx_Staging.pdf)

#### Treatment Options

[Video](https://www.youtube.com/watch?v=Tk8cp3uL-lU)&nbsp; &nbsp; &nbsp; &nbsp; [Slides](slides/04-Eso_Rx_Options.html) &nbsp; &nbsp; &nbsp; &nbsp; [Handout](slides/04-Eso_Rx_Options.pdf)

#### Early Stage Esophageal Cancer

&nbsp; &nbsp; &nbsp; &nbsp; [Slides](slides/06-Eso_Early.html) &nbsp; &nbsp; &nbsp; &nbsp; [Handout](slides/06-Eso_Early.pdf)


#### Surgery for Esophageal Cancer

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/12-Eso_Surgery.html) &nbsp; &nbsp; &nbsp; &nbsp; [Handout](slides/12-Eso_Surgery.pdf)  &nbsp; &nbsp; &nbsp; &nbsp; 

#### Choosing a Surgeon for Esophagectomy

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/32-Surgeon.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/32-Surgeon.pdf)

#### Nutrition for Esophageal Cancer Treatment

[Video](https://www.youtube.com/watch?v=XsqL41lU29w&t=23s) &nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/22-NutritionEsoCa.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/22-NutritionEsoCa.pdf)

#### Gastrostomy for Nutritional Support

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/24-Gastrostomy.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/24-Gastrostomy.pdf)

#### Exercise and Cancer Surgery

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/34-Exercise.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/34-Exercise.pdf)

#### Advanced Esophageal Cancer

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/08-Eso_Advanced.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/08-Eso_Advanced.pdf)

#### Locally Advanced Esophageal Cancer

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/14-Eso_Locally_Advanced.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/14-Eso_Locally_Advanced.pdf)


#### Metastatic Esophageal Cancer

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/16-Eso_Metastatic.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/16-Eso_Metastatic.pdf)


#### Central Venous Port for Chemotherpy

&nbsp; &nbsp; &nbsp; &nbsp;[Slides](slides/26-Port.html) &nbsp; &nbsp; &nbsp; &nbsp;[Handout](slides/26-Port.pdf)
