---
title: "GI Canced Education Slides"
output: html_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

Videos are available on YouTube: https://www.youtube.com/channel/UC5Deez8jUMnLhcf72-c

[Introduction to Levine Cancer Institute](slides/01-intro_LCI.pdf)


## Esophageal Cancer 

[Diagnosis/Staging](slides/02-Eso_Dx_Staging.pdf)

[Treatment Overview](slides/04-Eso_Rx_Options.pdf)

[Early Stage Disease](slides/06-Eso_Early.pdf)

Localized Disease

-   [Surgery for Esophagectomy Cancer](slides/12-Eso_Surgery.pdf)
-   [Choosing a Surgeon](slides/32-Surgeon.pdf)
-   [Exercise](slides/34-Exercise.pdf)

[Advanced Stage Disease](slides/08-Eso_Advanced.pdf)

-   [Locally Advanced](slides/14-Eso_Locally_Advanced.pdf)
  -   [Central Venous Port](slides/26-Port.pdf)
  -   [Surgery for Esophagectomy Cancer](slides/12-Eso_Surgery.pdf)
  -   [Choosing a Surgeon](slides/32-Surgeon.pdf)
  -   [Exercise](slides/34-Exercise.pdf)
  -   [Nutrition for Esophageal Cancer Treatment](slides/22-NutritionEsoCa.pdf)
  -   [Gastrostomy Tube for Nutritional Support](slides/24-gastrostomy.pdf)

-   [Metastatic Esophageal Cancer](slides/16-Eso_Metastatic.pdf)
  -   [Central Venous Port](slides/26-Port.pdf)
  -   [Nutrition for Esophageal Cancer Treatment](slides/22-NutritionEsoCa.pdf)
  -   [Gastrostomy Tube for Nutritional Support](slides/24-gastrostomy.pdf)
  
## Gastric (Stomach) Cancer 


