---
title: "GI Canced Education Slides"
output: html_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

Videos are available on YouTube: https://www.youtube.com/channel/UC5Deez8jUMnLhcf72-c

[Introduction to Levine Cancer Institute](slides/01-intro_LCI.html)



## Esophageal Cancer {.tabset}

### Diagnosis/Staging

```{r}
knitr::include_url("slides/02-Eso_Dx_Staging.html")
```

### Treatment Options

```{r}
knitr::include_url("slides/04-Eso_Rx_Options.html")
```


### Early Stage Disease

```{r}
knitr::include_url("slides/06-Eso_Early.html")
```

### Advanced Stage Disease
```{r}
knitr::include_url("slides/08-Eso_Advanced.html")
```

### Locally Advanced
```{r}
knitr::include_url("slides/14-Eso_Locally_Advanced.html")
```


### Metastatic Disease
```{r}
knitr::include_url("slides/16-Eso_Metastatic.html")
```


### Metastatic Disease
```{r}
knitr::include_url("slides/16-Eso_Metastatic.html")
```

## Surgery {.tabset}

### Esophagectomy

```{r}
knitr::include_url("slides/12-Eso_Surgery.html")
```

### Choosing a Surgeon
```{r}
knitr::include_url("slides/32-Surgeon.html")
```



## Supportive {.tabset}

### Nutrition

```{r}
knitr::include_url("slides/22-NutritionEsoCa.html")
```

### Gastrostomy Tube

```{r}
knitr::include_url("slides/24-gastrostomy.html")
```


### Central Venous Port

```{r}
knitr::include_url("slides/26-Port.html")
```


### Exercise

```{r}
knitr::include_url("slides/34-Exercise.html")
```
