---
title: "Early Stage Esophgaeal Cancer"
subtitle: "Jonathan Salo MD"
author: "[Levine Cancer Institute](https://atriumhealth.org/medical-services/specialty-care/cancer-care/esophageal-cancer/meet-the-team#)"
institute: "1021 Morehead Medical Drive, Charlotte NC<br>(980) 442-6410"
date: "<small>Click Right Arrow &#8594; to Begin</small>"
#date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    #toc: yes
    fig_caption: yes
    df_print: kable
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
  html_document: default
params: 
  pdf_param:TRUE
always_allow_html: yes     
---
<style type="text/css">
.remark-slide-content {
    font-size: 44px;
    padding: 1em 4em 1em 4em;
}

.title-slide h1:nth-of-type(1) {
}
.title-slide h2:nth-of-type(1) {
}
.title-slide a:nth-of-type(1) {
    color: #99ccff ;
    text-decoration: underline;
}

</style>
<!--- P10000266--->
<!--- Intro_02--->
```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "share_again", "animate_css", "tachyons","fit_screen","broadcast","scribble"))
```
I'm Dr Jonathan Salo, a  Cancer Surgeon at the Levine Cancer Institute.

.font60[If you’re seeing this video, it’s likely because you have an upcoming consultation scheduled.]

[Plan](00-Esophagus_Plan.pdf)

---

Early Stage cancers are those that are T1 or T2 and N0M0.  

If these are not familiar concepts please refer to videos which discuss staging.

---

In short, early stage cancers consist of small tumors without involvement of the lymph nodes, and they are either T1 or T2.

T1 tumors are treated very differently from T2 tumors, to it is important to distinguish between the two.

---

# Endoscopic Ultrasound

Endoscopic ultrasound is the best test to distinguish T1 tumors from T2 tumors. From a patient's perspective it's very similar to an upper endoscopy.  Under sedation, the gastroenterologist places a scope through the mouth into the esophagus.  The difference is that at the end of the scope, there is located a tiny ultrasound probe, which can take pictures of the wall of the esophagus and measure the tumor in the esophagus.

---

The endoscopic ultrasound will give one of three answers:

T1 tumor -> can frequently be treated through the endoscope, without the need for surgery. We'll discuss that more later

T2 -> Are usually treated with surgery

T3 -> Treated with a combination of chemotherapy

---

# T1 Esophageal Cancers

T1 tumors involve only the mucosa, the layer on the inner surface of the esophagus.  Because these tumors do not invade deeply, it is often possible to remove them using a scope. In some cases, the tumor can be treated without the need for surgery.  Endoscopic removal of tumor is called _endoscopic mucosal resection_

---

# Endoscopic Musocal Resection

For the patient's perspective, the procedure is similar to an endoscopy, which is done under sedation. Fluid is injected underneath the tumor, which raises a sort of blister.  The top layer (and the tumor) are then removed. The procedure is done as an outpatient.

---

# Pathology

The pathologist then examines the specimen to see whether the tumor has been removed completely

---

(favorable)  In an ideal circumstance, the tumor is confined to the center of the area which has been removed, ensuring that there is no tumor left behind.

A tumor is judged to be favorable for endoscopic mucosal resection if the tumor appears to be slow growing and the margins are clear, which suggests that the tumor was completely removed.

---

# Surveillance

When a small tumor has been completely removed by endoscopic mucosal resection, frequently no further therapy is required.  In this case, follow up endoscopy is recommended to be certain that there is no recurrence.

---
**Unfavorable**: If a tumor is removed with endoscopic mucosal resection and it appears as though the tumor may not have been completely removed *or* is more rapidly growing, this is considered an *unfavorable* outcome.  In this care there are two options:

1. surgical removal with esophagectomy or 
2. close surveillance with endoscopy.

---

If you or a family member have had an encounter with esophageal cancer surgery, I would love to hear about your experience, so please take a minute to leave a comment below. We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.

---

Here are some additional videos you may find helpful:


[Surgery for Esophageal Cancer](12-Eso_surgery.pdf)
