---
title: "Metastatic Esophageal Cancer"
subtitle: "Jonathan Salo MD"
author: "[Levine Cancer Institute](https://atriumhealth.org/medical-services/specialty-care/cancer-care/esophageal-cancer/meet-the-team#)"
institute: "1021 Morehead Medical Drive, Charlotte NC<br>(980) 442-6410"
date: "<small>Click Right Arrow &#8594; to Begin</small>"
#date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
  pdf_document:
    includes:
      in_header: preamble.tex
    toc: yes
    fig_caption: yes
    df_print: kable
  html_document: 
      ratio: "16:9"
always_allow_html: yes     
---
<style type="text/css">
.remark-slide-content {
    font-size: 40px;
    padding: 1em 4em 1em 4em;
}

.title-slide h1:nth-of-type(1) {
}
.title-slide h2:nth-of-type(1) {
}
.title-slide a:nth-of-type(1) {
    color: #99ccff ;
    text-decoration: underline;
}

</style>
<!--- --->
<!--- --->
```{r xaringanExtra, echo=FALSE, warning=FALSE, comment='', message=FALSE}
library(knitr)
xaringanExtra::use_xaringan_extra(c("tile_view", "share_again", "animate_css", "tachyons","fit_screen","broadcast","scribble"))
```
I'm Dr Jonathan Salo, a  Cancer Surgeon at the Levine Cancer Institute.

In this video, you will learn about the treatment of metastatic esophageal cancer.

[Plan](00-Esophagus_Plan.pdf)

---

Metastatic esophageal cancer is cancer that has spread to other organs such as the liver, lungs, or bone.

The primary treatment for metastatic esophageal cancer is chemotherapy, which is usually given intravenously.

---

The first step will be staging scans such as a CT scan or PET scan.  If you haven't done so already, please take a look at our video that talks about these scans [Advanced Esophageal Cancer](08-Eso_Advanced.html)

---

The next step will be meeting with a *Medical Oncologist* to develop a treatment plan.

---

If you have had difficulty eating or weight loss, you may need a feeding tube to help maintain your nutrition.  Please see our video on nutrition during esophageal cancer treatement [Nutrition in Esophageal Cancer](22-NutritionEsoCa.html)

---

Because most ot the chemotherapy drugs are administered intravenously, you may need a central venous port [Central Venous Port](26-Port.html)


---

If you or a family member have had an encounter with esophagal cancer, I would love to hear about your experience, so please take a minute to leave a comment below. We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.

---

Here are some additional videos you may find helpful:

[Central Venous Port for Chemotherapy](26-Port.html)
[Nutrition in Esophageal Cancer](22-NutritionEsoCa.html)

---
