---
title: "Central Venous Port for Chemotherapy"
subtitle: "Jonathan Salo MD"
author: "[Levine Cancer Institute](https://atriumhealth.org/medical-services/specialty-care/cancer-care/esophageal-cancer/meet-the-team#)"
institute: "1021 Morehead Medical Drive, Charlotte NC<br>(980) 442-6410"
date: "<small>Click Right Arrow &#8594; to Begin</small>"
#date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    toc: yes
    fig_caption: yes
    df_print: kable
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
  html_document: default
params: 
  pdf_param:TRUE
always_allow_html: yes     
---
<style type="text/css">
.remark-slide-content {
    font-size: 40px;
    padding: 1em 4em 1em 4em;
}

.title-slide h1:nth-of-type(1) {
}
.title-slide h2:nth-of-type(1) {
}
.title-slide a:nth-of-type(1) {
    color: #99ccff ;
    text-decoration: underline;
}

</style>
<!--- P10000266--->
<!--- Premiere: Intro_02--->
```{r xaringanExtra, echo=FALSE, warning=FALSE, comment='', message=FALSE}
library(knitr)
xaringanExtra::use_xaringan_extra(c("tile_view", "share_again", "animate_css", "tachyons","fit_screen","broadcast","scribble"))
```
# Introduction

Esophageal cancer is frequently treated with chemotherapy. A central venous port can make that easier.


I’m Dr Jonathan Salo, I’m a GI Cancer Surgeon.

In this video you’ll learn about a central venous port, which is used to administer chemotherapy.

---

Most chemotherapy for esophageal cancer is administered into a vein.  Because some of the chemotherapy can be irritating to the veins, it can be easier for some patients to have a central venous port placed.

The port is surgically placed under the skin, and is completely implanted just underneath the skin.  You can shower, bath, and even swim with the port in place.

---

The port contains a small chamber into which a needle can be placed when it is time to use the port.  A thin tube, or catheter, leads into a large blood vessel.

---

When it comes time for chemotherapy, the nurses can easily access the port with a needle that goes through the skin into the port, rather than placing an intravenous needle in a vein.  The drugs can then be administered directly into the bloodstream. If blood needs to be drawn for tests, this can also be done through the port.

---

Typically, the port is placed in the operating room under sterile conditions.  A 1 inch incision made below the collar bone, and frequently a smaller incision is made in the neck. The procedure is done an an outpatient, so you can go home the same day.

---

The care of a port after surgery is very easy, as there are no tubes outside the body to worry about.

The sutures are all under the skin and will dissolve on their own.  The incision should be dry for at least 24 hours. We recommend no heavy lifting for the first week to avoid bruising. 

---

Typially, the incisions will be covered with a surgical glue which will flake off after a week or so. 

For patients with difficulty eating, a feeding tube can be placed at the same time as the port.

---

If you or a family member have had experience with a central venous port, I would love to hear about it, so please take a minute to leave a comment below. We're constantly creating new videos, so please subscribe to be notified of new videos when we post them.

---

Here are some additional videos you may find helpful:

[Locally Advanced Esophageal Cancer](13-Eso_Locally_Advanced.html)

---

